volumes:
  dataToHost:

services:

    client:
        image: ghcr.io/werto87/game_01_client/modern-durak-client
        volumes:
            - dataToHost:/client
        command: sh -c "sed -i  's;{{WEBSOCKET-URL}};${WEBSOCKET_URL};' /client/project.html"
    server:
        image: ghcr.io/werto87/game_01_server/modern-durak-server
        ports:
         - 55555:55555
        volumes:
         - ${SECRETS_FOLDER}:/secrets
    nginx: 
        image: nginx:latest
        volumes:
          - ${NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf
          - ${SECRETS_FOLDER}:/secrets
          - dataToHost:/client    
        ports:
            - 80:80
            - 443:443
